// AUTO-GENERATED by npm run sync:galleries — do not edit by hand
// Generated: 2026-05-22T20:23:10.670Z

import type { Gallery } from './galleries';

export const galleriesGenerated: Gallery[] = [
  {
    categorySlug: 'wedding',
    photos: [

    ],
  },
  {
    categorySlug: 'maternity',
    photos: [
      { src: 'maternity3-1_smhqde', alt: 'Maternity Shoot — photo 1', width: 4000, height: 5000 },
    ],
  },
  {
    categorySlug: 'baby-photoshoot',
    photos: [
      { src: 'SailTheme04-1_p06tr9', alt: 'Baby Photoshoot — photo 1', width: 3657, height: 5486 },
      { src: 'Kutty001-1.jpg_h7kn7t', alt: 'Baby Photoshoot — photo 2', width: 3665, height: 4581 },
      { src: 'BabyBoho07-1_vvwi1t', alt: 'Baby Photoshoot — photo 3', width: 3427, height: 4284 },
      { src: 'Kalai035345_dnhnal', alt: 'Baby Photoshoot — photo 4', width: 4866, height: 3893 },
      { src: 'SailTheme03-1_y1u8hf', alt: 'Baby Photoshoot — photo 5', width: 4430, height: 3544 },
      { src: 'Kids1001-1_t6iwuc', alt: 'Baby Photoshoot — photo 6', width: 5000, height: 4000 },
      { src: 'Jungle001-66_dmtlgq', alt: 'Baby Photoshoot — photo 7', width: 3949, height: 5923 },
      { src: 'BabyBoho12-1_uxwaxy', alt: 'Baby Photoshoot — photo 8', width: 5515, height: 3677 },
      { src: 'Jungle001-39_eezmzq', alt: 'Baby Photoshoot — photo 9', width: 5923, height: 3949 },
    ],
  },
  {
    categorySlug: 'birthday',
    photos: [
      { src: 'Pariaarclicks009_yp3bp8', alt: 'Birthday — photo 1', width: 4898, height: 3265 },
      { src: 'Sanjeev0018-7_zceo5u', alt: 'Birthday — photo 2', width: 5000, height: 4000 },
      { src: 'Sanjeev0017-1_lu2ehb', alt: 'Birthday — photo 3', width: 3275, height: 4094 },
      { src: 'KEN08wo2-1_lfnlqt', alt: 'Birthday — photo 4', width: 3494, height: 4368 },
      { src: 'Sanjeev006-1_io9g5i', alt: 'Birthday — photo 5', width: 7124, height: 5700 },
      { src: 'ArakonamDR016-1_refjaq', alt: 'Birthday — photo 6', width: 4476, height: 2984 },
      { src: 'Levini012-1_cnk0ci', alt: 'Birthday — photo 7', width: 4000, height: 6000 },
      { src: 'Levini010-1_j5w9qa', alt: 'Birthday — photo 8', width: 4000, height: 6000 },
      { src: 'Birthday1009-1_ktpobz', alt: 'Birthday — photo 9', width: 6000, height: 4000 },
      { src: 'birthday001-1_lxfr0q', alt: 'Birthday — photo 10', width: 3576, height: 4470 },
    ],
  },
  {
    categorySlug: 'family-photoshoot',
    photos: [
      { src: 'Kids00008Latye10-1_sgfmfu', alt: 'Family Photoshoot — photo 1', width: 4000, height: 5000 },
      { src: 'Boho22-1_qqppbs', alt: 'Family Photoshoot — photo 2', width: 3829, height: 4786 },
      { src: 'Birthday1009-1_iesjjw', alt: 'Family Photoshoot — photo 3', width: 6000, height: 4000 },
      { src: 'Kidsa012-1_kmdspb', alt: 'Family Photoshoot — photo 4', width: 4000, height: 6000 },
      { src: 'Photo14-1_cvxflu', alt: 'Family Photoshoot — photo 5', width: 5000, height: 4000 },
      { src: 'Vaalparai01101-12_snjd09', alt: 'Family Photoshoot — photo 6', width: 4000, height: 6000 },
      { src: 'Boho12-1_rzndih', alt: 'Family Photoshoot — photo 7', width: 3870, height: 4838 },
    ],
  },
  {
    categorySlug: 'celebrity',
    photos: [
      { src: 'TruptiRw11woborder-1_v3auwo', alt: 'Celebrity — photo 1', width: 4232, height: 5290 },
      { src: 'Riya027a_hijt0z', alt: 'Celebrity — photo 2', width: 4000, height: 5000 },
      { src: 'Sherly010-1a_jhqck4', alt: 'Celebrity — photo 3', width: 3902, height: 4878 },
      { src: 'MynaLatest01-1_lju0uc', alt: 'Celebrity — photo 4', width: 3256, height: 4070 },
      { src: 'PrajinDaugtr07-1_c7jklw', alt: 'Celebrity — photo 5', width: 4322, height: 5402 },
      { src: 'Photo11-1_qnzjk2', alt: 'Celebrity — photo 6', width: 3001, height: 3750 },
      { src: 'pario026-1_tfhzvc', alt: 'Celebrity — photo 7', width: 4292, height: 5365 },
      { src: 'PAR03625_copy_V3_psu0ca', alt: 'Celebrity — photo 8', width: 6000, height: 4000 },
      { src: 'riya-1_xvwb9r', alt: 'Celebrity — photo 9', width: 3827, height: 5750 },
      { src: 'AsihDutta02_1_rihqwg', alt: 'Celebrity — photo 10', width: 2386, height: 1909 },
      { src: 'Ajay001-1_1_m9rz40', alt: 'Celebrity — photo 11', width: 3941, height: 4926 },
      { src: 'green2-1_2_aqpe48', alt: 'Celebrity — photo 12', width: 4800, height: 6000 },
      { src: 'Pariaarclicks0013_lb5jsx', alt: 'Celebrity — photo 13', width: 3265, height: 4898 },
      { src: 'Photo1-1_dmevyi', alt: 'Celebrity — photo 14', width: 3899, height: 2687 },
      { src: 'AsihDutta05_2_dkqjfh', alt: 'Celebrity — photo 15', width: 2314, height: 1851 },
    ],
  },
];
