// AUTO-GENERATED by npm run sync:galleries — do not edit by hand
// Run sync after uploading photos to Cloudinary folders.

import type { Gallery } from './galleries';

export const galleriesGenerated: Gallery[] = [
  { categorySlug: 'wedding', photos: [] },
  { categorySlug: 'maternity', photos: [] },
  { categorySlug: 'baby-photoshoot', photos: [] },
  { categorySlug: 'birthday', photos: [] },
  { categorySlug: 'family-photoshoot', photos: [] },
  { categorySlug: 'celebrity', photos: [] },
];
